backend:
  name: github
  repo: valentinfilimonov-cz/photo-portfolio
  branch: master
  base_url: https://photo-portfolio-mu.vercel.app
  auth_endpoint: api/auth

local_backend: true

site_url: http://localhost:3000

media_folder: public/images
public_folder: /images

collections:
  - name: "albums"
    label: "Albums"
    folder: "content/albums"
    create: true
    slug: "{{slug}}"
    extension: "json"
    format: "json"

    fields:
      - { label: "Title", name: "title", widget: "string" }

      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false
        }

      - {
          label: "Cover Image",
          name: "cover",
          widget: "image",
          required: false
        }

      - {
          label: "Images",
          name: "images",
          widget: "list",
          field: { label: "Image", name: "image", widget: "image" }
        }
